sf_tickets_user:
    resource: "@sfTicketsUsersBundle/Resources/config/routing.yml"
    prefix:   /

sf_tickets_tickets:
    resource: "@sfTicketsTicketsBundle/Resources/config/routing.yml"
    prefix:   /

sf_tickets_entities:
    resource: "@sfTicketsEntitiesBundle/Resources/config/routing.yml"
    prefix:   /

