parameters:
    sf_tickets_tickets.manager.class:     sfTickets\TicketsBundle\EntityManager\TicketManager
    sf_tickets_tickets.entity.class:          sfTickets\TicketsBundle\Entity\Ticket

services:
     sf_tickets_tickets.manager:
         class: %sf_tickets_tickets.manager.class%
         arguments:    ["@doctrine", "%sf_tickets_tickets.entity.class%"]
