parameters:
#    sf_tickets_tickets.example.class: sfTickets\TicketsBundle\Example

services:
#    sf_tickets_tickets.example:
#        class: %sf_tickets_tickets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
