parameters:
#    sf_tickets_entities.example.class: sfTickets\EntitiesBundle\Example

services:
#    sf_tickets_entities.example:
#        class: %sf_tickets_entities.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
