parameters:
#    sf_tickets_user.example.class: sfTickets\UsersBundle\Example

services:
#    sf_tickets_user.example:
#        class: %sf_tickets_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
